default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["RAILS_MAX_THREADS"] || 5 %>
  timeout: <%= ENV["DATABASE_TIMEOUT"] %>
  database: <%= ENV["DATABASE_NAME"] || ENV["RDS_DB_NAME"] %>
  username: <%= ENV["DATABASE_USERNAME"] || ENV["RDS_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] || ENV["RDS_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] || ENV["RDS_HOSTNAME"] %>
  port: <%= ENV["DATABASE_PORT"] || ENV["RDS_PORT"] %>

production:
  <<: *default

development:
  <<: *default

test:
  <<: *default
